services:
  email_processor:
    build: ./code
    container_name: email_processor
    ports:
      - "8000:8000"
    volumes:
      - ./code/src:/app/src
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - mongo

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - WEBHOOK_URL=http://localhost:5678/
    depends_on:
      - mongo
      - email_processor

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
